name: Deploy to HuggingFace Spaces

on:
  push:
    branches:
      - main
      - preprod

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push to HuggingFace Space (prod)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "ofer.brodatch@gmail.com"
          git config user.name "Brofer-The-First"
          git lfs install
          git checkout --orphan deploy
          git add -A
          git commit -m "Deploy"
          git remote add hf https://Brofer:${HF_TOKEN}@huggingface.co/spaces/Brofer/interview
          git push hf deploy:main --force

  deploy-preprod:
    if: github.ref == 'refs/heads/preprod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push to HuggingFace Space (preprod)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "ofer.brodatch@gmail.com"
          git config user.name "Brofer-The-First"
          git lfs install
          git checkout --orphan deploy
          git add -A
          git commit -m "Deploy"
          git remote add hf https://Brofer:${HF_TOKEN}@huggingface.co/spaces/Brofer/interview-preprod
          git push hf deploy:main --force
